import { CommentIcon, DelteIcon, DivideIcon, FoodIcon, HealthIcon, LikeIcon, MailIcon, PencilIcon, PrintingIcon, StarIcon, TransportIcon } from "../Icon";

export const Card = [
    {
        image: "/img/discountimg.png",
        profileimg: "/img/profile.png",
        core: "Core by Clare Smyth",
        heartimg: "/img/heart.png",
        dolarimg: "/img/dolar.png",
        dolartext: "Get 50% off Margarita from 8:00 PM to 9:00PM.",
        errorimg: "/img/i.png",
        errortext: "Terms and Conditions Apply.",
        btnn: <DivideIcon />,
        name: "Redeem",
    },
    {
        image: "/img/discountimg.png",
        profileimg: "/img/profile.png",
        core: "Core by Clare Smyth",
        heartimg: "/img/heart.png",
        dolarimg: "/img/dolar.png",
        dolartext: "Get 50% off Margarita from 8:00 PM to 9:00PM.",
        errorimg: "/img/i.png",
        errortext: "Terms and Conditions Apply.",
        btnn: <DivideIcon />,
        name: "Redeem",
    },
    {
        image: "/img/discountimg.png",
        profileimg: "/img/profile.png",
        core: "Core by Clare Smyth",
        heartimg: "/img/heart.png",
        dolarimg: "/img/dolar.png",
        dolartext: "Get 50% off Margarita from 8:00 PM to 9:00PM.",
        errorimg: "/img/i.png",
        errortext: "Terms and Conditions Apply.",
        btnn: <DivideIcon />,
        name: "Redeem",

    },
]
export const slidebar = [
    {
        transportimg: <TransportIcon />,
        transporttext: "Transport & Service",
    },
    {
        transportimg: <FoodIcon />,
        transporttext: "Food & Beverage",
    },
    {
        transportimg: <MailIcon />,
        transporttext: "Mall & Shopping",
    },
    {
        transportimg: <HealthIcon />,
        transporttext: "Healthcare & Beauty",
    },
    {
        transportimg: <PrintingIcon />,
        transporttext: "Parenting Fun",
    },
]
export const petrol = [
    {
        petrol: "/img/petrol.png",
        shell: "Shell Station - Bugis",
        profileimg2: "/img/profile.png",
        friendly: "“Friendly Crew”",
        star: [
            { starimg: <StarIcon /> },
            { starimg: <StarIcon /> },
            { starimg: <StarIcon /> },
            { starimg: <StarIcon /> },
            { starimg: <StarIcon /> },
        ],
        five: "5.0",
        like: <LikeIcon />,
        hundered: "100k",
        coment: <CommentIcon />,
    },
    {
        petrol: "/img/petrol.png",
        shell: "Shell Station - Bugis",
        profileimg2: "/img/profile.png",
        friendly: "“Friendly Crew”",
        star: [
            { starimg: <StarIcon /> },
            { starimg: <StarIcon /> },
            { starimg: <StarIcon /> },
            { starimg: <StarIcon /> },
            { starimg: <StarIcon /> },
        ],
        five: "5.0",
        like: <LikeIcon />,
        hundered: "100k",
        coment: <CommentIcon />,
    },
    {
        petrol: "/img/petrol.png",
        shell: "Shell Station - Bugis",
        profileimg2: "/img/profile.png",
        friendly: "“Friendly Crew”",
        star: [
            { starimg: <StarIcon /> },
            { starimg: <StarIcon /> },
            { starimg: <StarIcon /> },
            { starimg: <StarIcon /> },
            { starimg: <StarIcon /> },
        ],
        five: "5.0",
        like: <LikeIcon />,
        hundered: "100k",
        coment: <CommentIcon />,
    },
    {
        petrol: "/img/petrol.png",
        shell: "Shell Station - Bugis",
        profileimg2: "/img/profile.png",
        friendly: "“Friendly Crew”",
        star: [
            { starimg: <StarIcon /> },
            { starimg: <StarIcon /> },
            { starimg: <StarIcon /> },
            { starimg: <StarIcon /> },
            { starimg: <StarIcon /> },
        ],
        five: "5.0",
        like: <LikeIcon />,
        hundered: "100k",
        coment: <CommentIcon />,
    },
    {
        petrol: "/img/petrol.png",
        shell: "Shell Station - Bugis",
        profileimg2: "/img/profile.png",
        friendly: "“Friendly Crew”",
        star: [
            { starimg: <StarIcon /> },
            { starimg: <StarIcon /> },
            { starimg: <StarIcon /> },
            { starimg: <StarIcon /> },
            { starimg: <StarIcon /> },
        ],
        five: "5.0",
        like: <LikeIcon />,
        hundered: "100k",
        coment: <CommentIcon />,
    },
    {
        petrol: "/img/petrol.png",
        shell: "Shell Station - Bugis",
        profileimg2: "/img/profile.png",
        friendly: "“Friendly Crew”",
        star: [
            { starimg: <StarIcon /> },
            { starimg: <StarIcon /> },
            { starimg: <StarIcon /> },
            { starimg: <StarIcon /> },
            { starimg: <StarIcon /> },
        ],
        five: "5.0",
        like: <LikeIcon />,
        hundered: "100k",
        coment: <CommentIcon />,

    },
]
export const table = [
    {
        profileimg: "/img/profile.png",
        itemname: "Item Name",
        itemdescription: "Item Description ",
        active: "Active",
        main: "Main",
        vegan: "Vegan",
        dolar: "$12",
        drink: "Vegan Drinks",
        gram: "100 grams",
        delete: <DelteIcon />,
        penil: <PencilIcon />,
    }
]
